core/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('singup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html', authentication_form =LoginForm), name='login'),
    path('logout/', views.user_logout, name='logout'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/reserve_car', views.reserve_car, name='reserve_car'),
    #path('<int:pk>/res_confirm', views.res_confirm , name='res_confirm'),
    path('res', views.user_reservations, name='user_reservations'),
    path('<int:pk>/cancel' , views.user_canc_reservation, name='user_canc_reservation'),
    path('dash', views.admin_dash, name='admin_dash'),
    path('<int:pk>/dele', views.admin_dele_res, name='admin_dele_res'),

]

site_de_location_de_voiture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from item.views import reserve_car


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),

    
] +static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

item/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class types(models.Model):
    car_type = models.CharField(max_length=50)
    
    def __str__(self):
        return self.car_type
    

class Cars(models.Model):
    make = models.CharField(max_length=50)
    model = models.CharField(max_length=50)
    year = models.IntegerField()
    color = models.CharField(max_length=20)
    rent_price = models.DecimalField(max_digits=8, decimal_places=2 , null = False , default='0.00')
    image = models.ImageField(upload_to='item_images', blank= False, null=False,default='no image')
    is_reserved = models.BooleanField(default=False)
    categories = models.ForeignKey(types, related_name='items', on_delete= models.CASCADE, default='1')

    class Meta:
        verbose_name_plural = 'Cars'

    def __str__(self):
        return f"{self.year} {self.make} {self.model}" 

class Reservation(models.Model):
    car = models.ForeignKey(Cars, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    


    
        

item/forms.py
from django import forms
from .models import Reservation, Cars
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class ReservationForm(forms.ModelForm):

    class Meta:
        model = Reservation
        fields = ['car','start_date', 'end_date']
        car= forms.ChoiceField

    start_date = forms.DateField(widget=forms.TextInput(attrs={
         'type': 'date' , 'class':'w-full py-4 px-6 rounded-xl'
    }))

    end_date = forms.DateField(widget=forms.TextInput(attrs={
         'type': 'date' , 'class':'w-full py-4 px-6 rounded-xl'
    }))

    def clean(self):
        cleaned_data = super().clean()
        car = cleaned_data.get('car')
        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
       

        if car and start_date and end_date:
    
            reservations = Reservation.objects.filter(car=car, end_date__gt=start_date, start_date__lt=end_date)
            if reservations.exists():
                 raise ValidationError('The car is already reserved for the selected dates. Please choose another reservation date.')
         
                

item/views.py
from django.shortcuts import get_object_or_404, render ,redirect
from .models import Cars, Reservation,types
from django.contrib.auth.decorators import login_required
from .forms import ReservationForm
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect ,HttpResponseForbidden
from django.contrib.auth.models import User


# Create your views here.
def detail(request, pk):
    item = get_object_or_404(Cars, pk=pk)

    return render(request, 'cars/detail.html', {
        'cars': item
    })

@login_required
def reserve_car(request, pk):
    car = get_object_or_404(Cars, pk= pk)
    if request.method == 'POST':  
        form = ReservationForm(request.POST)
        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.user = request.user
            reservation.car = car
            car.is_reserved = True
            car.save()
            reservation.save()
            return HttpResponseRedirect('/items/res')
             
    else:
        
        form = ReservationForm()
        form.fields['car'].queryset = Cars.objects.filter(pk=pk)
    return render(request, 'cars/reserve_car.html', {
        'cars': car , 'form': form 
        })




@receiver(post_delete, sender=Reservation)
def no_reservation(sender, instance, **kwargs):
    car = instance.car
    car.is_reserved = False
    car.save()

def items(request):
    query = request.GET.get('query', '')
    car = Cars.objects.filter(is_reserved=False)
    categories= types.objects.all()
    types_id=request.GET.get('types', 0)
    if query:
        car = car.filter(Q(make__icontains=query)|Q(model__icontains=query))
    if types_id :
        car = car.filter(categories=types_id)

    return render(request , 'cars/items.html',{
        'cars': car ,
        'query' : query,
        'types' : categories,
        'types_id': int(types_id)
        
    })

@login_required
def user_reservations(request):
    reservations = Reservation.objects.filter(user=request.user)
    return render(request, 'cars/user_reservation.html', {
        'reservations': reservations,
        
        })


@login_required
def user_canc_reservation(request, pk):
    reservation = get_object_or_404(Reservation , pk=pk , user = request.user)
    if request.method == 'POST':
        reservation.car.is_reserved = False
        reservation.car.save()
        reservation.delete()
        messages.success(request , "Your reservation has been deleted ")
        return HttpResponseRedirect('/items/res')
        
    else :
        return render(request, 'cars/reservation_cancel.html', {
            'reservation': reservation,
        })
    

@login_required
def admin_dash(request):
    if request.user.is_staff:
        reservation = Reservation.objects.all()
        users= User.objects.all()
        return render(request, 'cars/admin_dash.html', {'reservations': reservation, 'users': users})
    else:
            return HttpResponseForbidden()

@login_required
def admin_dele_res(request , pk):
        reservation = get_object_or_404(Reservation, pk=pk)
        reservation.car.is_reserved = False
        reservation.car.save()
        reservation.delete()
        return HttpResponseRedirect('/items/dash')

item/templates/cars/admin_dash.html
{% extends 'core/base.html'%}
{% block content  %}

<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2 class="mb-12 text-2xl text-center"><strong> Reservations </strong> </h2>
    {% for reservations in reservations %}
    <tr>
      <p class = "text-gray-500 mt-6"> <strong> User: {{ reservations.user }}</strong></p>
      <p class = "text-gray-500"> <strong> Reservation ID: {{ reservations.id }}</strong></p>
      <p class = "text-gray-500"> <strong> Car: {{ reservations.car }} <strong></p>
      <p class = "text-gray-500"><strong> Start date:{{ reservations.start_date }}</strong></p>
      <p class = "text-gray-500 mb-6"><strong> end date: {{ reservations.end_date }}</strong></p>
      <a href="{% url 'item:admin_dele_res' reservations.id %}" class=" px-9 p-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-red-700 mt-6 mb-6">Cancel</a>

      
    </tr>
    {% endfor %}
  </div>

<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  <h2  class="mb-12 text-2xl text-center"> <strong>List of users </strong></h2>
  <tr>
    {% for users in users %}
    <p class = "text-gray-500 mb-6"><strong>{{ users.username }}</strong></p>
    {% endfor %}
  </tr>
</div>
  {% endblock  %}

item/templates/cars/admin_dele.html
{% extends 'core/base.html' %}

{% block content %}
<h1>Delete Reservation</h1>
<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <p class = "text-red-500"><strong>Are you sure you want to Cancel this reservation?</Strong>
    <ul>
    <li class = "py-2 px-2 ">Car: {{ reservation.car }}</li>
    <li class = "py-2 px-2">Start date: {{ reservation.start_date }}</li>
    <li class = "py-2 px-2">End date: {{ reservation.end_date }}</li>
    </ul>
 
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button class="m-6 px-9 p-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-red-700" type="submit">Submit </button>
  </form>
</div>

{% endblock %}

item/templates/cars/detail.html
{%extends 'core/base.html' %}
{% block title %}{{ cars.make }}{% endblock %} 
{% block content%}
<div class ="grid grid-cols-5 gap-6">
    <div class = "col-span-3">
        <img src = {{cars.image.url}} class="rounded-xl">
    </div>
    <div class = "col-span-2 p-9 bg-gray-200 rounded-xl">
       <h1 class="mb-6 text-3xl">{{ cars.make }} {{cars.model}} {{cars.year}}</h1> 
       <p class ="mb-6 text-3xl"><strong>Color: </strong>{{cars.color}}</p>
       <p class ="mb-6 text-3xl"><strong>Categorie: </strong>{{cars.categories}}</p>
       <p class="mb-6 text-3xl"><strong>Rent Price: </strong>{{cars.rent_price}} DH per day </p>
       <div class = "col-span-2 p-22 py-20 bg-gray-200 rounded-xl ">
        {% if request.user.is_authenticated %}
        <a href="{% url 'item:reserve_car' cars.id %}" class="px-9 p-3  text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-{{ cars.color }}-700">Reserve</a>
        {% else %}
        <p class="mb-6 text-3xl">you have to login to reserve</p> 
        {%endif%}
       </div>
    </div>
</div>    
{%endblock%}

item/templates/cars/items.html
{% extends 'core/base.html'%}

{% block title %}Cars{% endblock %}

{% block content %}
    <div class ="pb-6 grid grid-cols-4 gap-4 bg-gray-200">
        <div class ="col-span-1">
            <form method="get" action = "{% url 'item:items' %}">
                <input name ="query" class ="w-full py-4 px-6 border rounded-xl" type="text" value ="{{query}}" placeholder="you can look up for a car here">
                <button class = "mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class= "my-6" >
            <p class = "font-semibold">Categories</p>
            <ul>
                {% for types in types %}
                    <li class = "py-2 px-2 rounded-xl{% if types.id == types_id %} bg-gray-300 {% endif %}"> 
                        <a href = "{% url 'item:items' %}?query={{query}}&types={{types.id}}" >{{types.car_type}}</a>
                    </li>
                {%endfor%}
            </ul>
        </div>
        <div class = " col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {%for cars in cars %}
                    <div>
                        <a href="{% url 'item:detail' cars.id %}">
                            <div>
                                <img src= "{{ cars.image.url }}" class="rounded-t-xl">
                                
                            </div>
    
                            <div class ="p-6 bg-white rounded-b-xl">
                                <h2 class= "text-2xl">{{ cars.make }}</h2>
                                
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

    </div>

{% endblock %}

item/templates/cars/reservation_cancel.html
{% extends 'core/base.html' %}

{% block content %}
<h1>Cancel Reservation</h1>
<div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <p class = "text-red-500"><strong>Are you sure you want to Cancel this reservation?</Strong>
    <ul>
    <li class = "py-2 px-2 ">Car: {{ reservation.car }}</li>
    <li class = "py-2 px-2">Start date: {{ reservation.start_date }}</li>
    <li class = "py-2 px-2">End date: {{ reservation.end_date }}</li>
    </ul>
 
  <form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ request.path }}">
    <button class="m-6 px-9 p-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-red-700" type="submit">Submit </button>
  </form>
</div>

{% endblock %}

item/templates/cars/reserve_car.html
{%extends 'core/base.html'%}
{% block title %}{{ cars.make }} {{cars.model}} Resevation{% endblock %} 
{% block content %}
<div class ="grid grid-cols-5 gap-6">
  <div class = "col-span-3">
  <img src = {{cars.image.url}} class="rounded-xl">
  </div>

  <div class = "col-span-2 p-9 bg-gray-200 rounded-xl">
    <form method="post">
      <h1 class="mb-6 text-3xl"><strong>Reserve {{ cars.make }} {{ cars.model }}</strong></h1>  
      <p>Price: {{ cars.rent_price }}/day</p> 
      {% csrf_token %}
      {{ form.as_p }}
      {% if form.errors %}
    <div class="col-span-2 p-9 bg-gray-200 rounded-xl">
        <ul>
            {% for field_errors in form.errors.values %}
                {% for error in field_errors %}
                    <li class="mb-6 text-3xl text">{{ error }}</li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}
      <button class="m-6 px-9 p-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-red-700" type="submit">Submit </button>
    </form>
  </div>  
</div>

{% endblock %}

item/templates/cars/user_reservation.html
{% extends 'core/base.html' %}
{% block title%} My Reservations {%endblock%}
{% block content %}
  <h1>My Reservations</h1>
  <div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
  {% if reservations %}
    <ul>
      {% for reservation in reservations %}
      <li class = "mt-6 py-2 px-2 rounded-xl"> <strong>Car</strong> : {{ reservation.car }} </li>
      <li class = "py-2 px-2 rounded-xl">  <strong>Reservation start </strong>: {{ reservation.start_date }} </li>
      <li class = "mb-6 py-2 px-2 rounded-xl">  <strong>Reservation end </strong> : {{ reservation.end_date }} </li>
      <a href="{% url 'item:user_canc_reservation' reservation.id %}" class=" px-9 p-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-red-700">Cancel</a>
      {% endfor %}
    </ul>
  </div>
  {% else %}
    <p>You have no reservations.</p>
  {% endif %}
{% endblock %}