core/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views
app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('singup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='core/login.html', authentication_form =LoginForm), name='login'),
    path('logout/', views.user_logout, name='logout'),
]

item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/reserve_car', views.reserve_car, name='reserve_car'),
    #path('<int:pk>/res_confirm', views.res_confirm , name='res_confirm'),
    path('res', views.user_reservations, name='user_reservations'),
    path('<int:pk>/cancel' , views.user_canc_reservation, name='user_canc_reservation'),
    path('dash', views.admin_dash, name='admin_dash'),
    path('<int:pk>/dele', views.admin_dele_res, name='admin_dele_res'),

]

site_de_location_de_voiture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from item.views import reserve_car


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('items/', include('item.urls')),

    
] +static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm , AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username= forms.CharField(widget=forms.TextInput(attrs={
    'placeholder':'Your username',
    'class':'w-full py-4 px-6 rounded-xl'

    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
    'placeholder':'Password',
    'class':'w-full py-4 px-6 rounded-xl'
    }))

class SingupForm(UserCreationForm):  
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username= forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class':'w-full py-4 px-6 rounded-xl'

    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your Email',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder':'Confirm your Password',
        'class':'w-full py-4 px-6 rounded-xl'
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Cars
from item.models import types
from .forms import SingupForm
from django.contrib.auth import logout
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
def index(request):
    car = Cars.objects.filter(is_reserved = False) [0:6]
    categories = types.objects.all()
    return render(request, 'core/index.html',{
        'car' :car,
        'categories' :categories,
    })
    

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST' :
        form = SingupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login')
    else:
        form = SingupForm()
    

    return render(request, 'core/signup.html', {
        'form':form
    })

def user_logout(request):
    logout(request)
    # Redirect to a success page
    return redirect('/''')

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset ="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">

            <script src="https://cdn.tailwindcss.com"></script>

            <title>{% block title %}{% endblock %} | Car Rental</title>
        </head>


        <body>
        <nav class ="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class= "text-xl font-semibold" > Car Rental </a>

            <div class="space-x-6">
                <a href="{% url 'item:items' %}" class ="text-lg font-semibold hover:text-red-500"> Browse </a>
                {% if request.user.is_authenticated %}
                <a href="{% url 'item:user_reservations' %}" class ="text-lg font-semibold hover:text-red-500"> Reservation</a>
                <a href="#" class="px-6 py-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                {% if request.user.is_staff %}
                <a href="{% url 'item:admin_dash' %}" class="px-6 py-3 text-lg font-demibold bg-red-500 text-white rounded-xl hover:bg-red-900">Dashboard</a>
                {%endif%}
                <a href="{% url 'core:logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-demibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-demibold bg-red-500 text-white rounded-xl hover:bg-red-900">Login</a>
                {%endif%}

            </div> 
        </nav>       
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-6 px-3 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gary-500">Welcome to our car rental site, where we provide you with a hassle-free and convenient way to rent a car for your next trip. Our site offers a wide selection of vehicles to choose from, including economy cars, SUVs, luxury cars, and more, all at competitive prices.With our easy-to-use booking platform, you can quickly and easily search for available vehicles, compare prices and features, and reserve your rental car in just a few clicks. We work with top car rental companies to provide you with a reliable and trustworthy rental experience, no matter where your travels take you.</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semmibold text-gray-400">Menu</h3>   
                
                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy</a></li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
                </ul>   
            
    </body>
</html>            

core/templates/core/contact.html
{%  extends 'core/base.html' %}
{% block content  %}
<h1> contact </h1> 
{%endblock%}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% block content %}<h1> Welcome </h1>

    <div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Available cars for Rent </h2>
         
        <div class="grid grid-cols-3 gap-3">
            {%for car in car %}
                <div>
                    <a href="{% url 'item:detail' car.id %}">
                        <div>
                            <img src= "{{ car.image.url }}" class="rounded-t-xl">
                            
                        </div>

                        <div class ="p-6 bg-white rounded-b-xl">
                            <h2 class= "text-2xl">{{ car.make }}</h2>
                            
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class ="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Car Categories </h2>
        

        <div class="grid grid-cols-3 gap-3">
                {% for categories in categories %}
                <a href="#">
                    <div class ="p-6 bg-white rounded-b-xl">
                        <h2 class= "text-2xl">{{ categories.car_type}}</h2>
                        <p class = "text-gray-500"> {{categories.items.count}}</p>
                    </div>
                </a>
                {% endfor %}
                
{% endblock %}

core/templates/core/login.html
{%  extends 'core/base.html' %}
{%block title%}Login{% endblock %}

{% block content %} 
<div class ="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded=xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="post" action ".">
        {%csrf_token%}

        <div class ="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>

        <div class ="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password}}
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {%endfor%}    

                {{ form.non_field_errors}}
            </div>
        {% endif %}  
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</div>
{%endblock%}

core/templates/core/signup.html
{%  extends 'core/base.html' %}
{%block title%}Sign up {% endblock %}

{% block content %} 
<div class ="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded=xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="post" action ".">
        {%csrf_token%}

        <div class ="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{form.username}}
        </div>

        <div class ="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{form.email}}
        </div>

        <div class ="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{form.password1}}
        </div>
        <div class ="mb-3">
            <label class="inline-block mb-2">confirm password</label><br>
            {{form.password2}}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {%endfor%}    

                {{ form.non_field_errors}}
            </div>
        {% endif %}  
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</div>
{%endblock%}